### ISSUE TITLE
Has been under development for too long.

### ISSUE THREAD

**Issue by quackduck** [Fortunate-MAN/EquationGraph#1]
How you doing, Ashish.

**Comment by double-fault** [comment]
Doing good. Don't even remember what this repo was for but seeing it now makes me nostalgic.

**Comment by quackduck** [comment]
So, what you working on nowadays?

**Comment by quackduck** [comment]
lol us using github issues as a chat

**Comment by double-fault** [comment]
*you

**Comment by quackduck** [comment]
lol
